steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/my-nodejs-app",
        "${_PATH}",
      ]

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/my-nodejs-app",
      ]

  # Deploy the Docker image to Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "my-nodejs-app",
        "--image",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/my-nodejs-app",
        "--region",
        "asia-southeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

substitutions:
  _SERVICE_NAME: "my-nodejs-app"
  _PATH: "."

images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/my-nodejs-app"
